### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by jmhodges** [w4/sonos.rs#5]
Hey, we're seeing build errors on linux with the currently released version that don't happen on master. It'd be cool for a new release top be cut!

**Comment by w4** [comment]
Hi Jeff, I'll get this sorted for you tomorrow, thanks

**Comment by w4** [comment]
Hey @jmhodges, this is resolved by 09992e816a9a16d84f720f8acdbf982dd30d19b2. I've also fixed an issue with the `Speaker::track()` method since `/status/topology` just returns an empty response now.

To be honest the whole lib needs revisiting; to comform to Sonos' API a bit better, support searching for tracks and support for futures since reqwest's default API is futures-based now. I'll get this done in 0.2.0 which I'll work on shortly.

Please feel free to open another issue if you find any issues while using the library.

**Comment by jmhodges** [comment]
Thanks!
